language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
branches:
  except:
    - gh-pages
matrix:
  fast_finish: true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install fping
  - sudo apt-get install traceroute
  - sudo apt-get install librrd-dev
install:
  - python -m pip install -U pip
  - pip install -U setuptools
  - pip install tox
  - pip install tox-travis
  - pip install codecov
script:
  - tox
after_success:
  - codecov
