
language: python
python: 3.5
branches:
  except:
    - gh-pages
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install fping
install:
  - wget https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install tox
  - pip install codecov
script:
  - tox -e $TOX_ENV
after_success:
  - codecov

