
language: python
python: 2.7
branches:
  except:
    - gh-pages
env:
  - TOX_ENV=py27
install:
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  - pip install tox
  - pip install codecov
script:
  - tox -e $TOX_ENV
after_success:
  - codecov

