
name: $(BuildDefinitionName):$(Date:yyyyMMdd)$(Rev:.rr)
resources:
  repositories:
  - repository: tox
    type: github
    endpoint: github
    name: tox-dev/azure-pipelines-template
    # master for py 3.8 and 3.9
    ref: master

trigger:
  batch: true
  branches:
    include:
    - azure_pipelines
    - master
    - refs/tags/*

pr:
  branches:
    include:
    - master

variables:
  PYTEST_ADDOPTS: "-v -v -ra --showlocals"
  CI_RUN: 'yes'

stages:
- stage: Test
  jobs:
  - template: run-tox-env.yml@tox
    parameters:
      jobs:
        # gevent doesn't work on python 3.9 yet
        # py39:
        #   image: [linux]
        py38:
          image: [linux, macOs]
        py37:
          image: [linux, macOs]
        py36:
          image: [linux, macOs]
        py35:
          image: [linux, macOs]
        py34:
          image: [linux]
        py27:
          image: [linux, macOS]
  #      dev: null
      before:
        - script: 'sudo apt-get update -y && sudo apt-get install fping librrd-dev traceroute'
          displayName: Install deps via apt-get
          condition: and(succeeded(), eq(variables['image_name'], 'linux'), startsWith(variables['TOXENV'], 'py'))
        - script: 'brew update -vvv && brew install fping rrdtool'
          displayName: Install deps via brew
          condition: and(succeeded(), eq(variables['image_name'], 'macOs'), startsWith(variables['TOXENV'], 'py'))
