
name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
resources:
  repositories:
  - repository: tox
    type: github
    endpoint: github
    name: tox-dev/azure-pipelines-template
    ref: refs/tags/0.2

trigger:
  batch: true
  branches:
    include:
    - azure_pipelines
    - master
    - refs/tags/*

pr:
  branches:
    include:
    - master

variables:
  PYTEST_ADDOPTS: "-v -v -ra --showlocals"
#  PYTEST_XDIST_PROC_NR: 'auto'
  CI_RUN: 'yes'

jobs:
- template: run-tox-env.yml@tox
  parameters:
    jobs:
#      fix_lint: null
#      docs: null
#      py38:
#        image: [linux]
#      py37:
#        image: [linux, windows, macOs]
      py27:
        image: [linux, macOS]
#      py36:
#        image: [linux, windows, macOs]
#      py35:
#        image: [linux, windows, macOs]
#      py34:
#        image: [linux, windows, macOs]
#      dev: null
    before:
      - script: 'sudo apt-get update -y && sudo apt-get install fping librrd-dev traceroute'
        displayName: install deps via apt-get
        condition: and(succeeded(), eq(variables['image_name'], 'linux'), in(variables['TOXENV'], 'py37', 'py36', 'py35', 'py34', 'py27'))
      - script: 'brew update -vvv && brew install fping rrdtool'
        displayName: install deps via brew
        condition: and(succeeded(), eq(variables['image_name'], 'macOs'), in(variables['TOXENV'], 'py37', 'py36', 'py35', 'py34', 'py27'))
